sudo: false
language: python

branches:
  only:
    - master
    - /^\d+\.\d+\.X$/

cache:
  directories:
    - $HOME/.cache/pip
    - .hypothesis

matrix:
  include:
    # Main tests on supported Python versions.
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.3"
      env: TOXENV=py33
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "pypy-5.3.1"
      env: TOXENV=pypy

    # Linting, docs, and other non-test stuff.
    - python: "3.4"
      env: TOXENV=lint
    - python: "3.5"
      env: TOXENV=docs

install:
  - "pip install -U pip setuptools"
  - "pip install -U tox"
script:
  - tox -- --hypothesis-profile travis
